- name: Install web server
  apt:
    name: "apache2"
    state: present

- name: Create document root for web service
  file:
    path: "{{ www_data_path }}"
    state: directory
    owner: "{{ www_owner_deb }}"
    group: "{{ www_group_deb }}"
    mode: "{{ www_data_path_perm }}"

- name: Write index file to web service root
  copy:
    src: "{{ www_index_file }}"
    dest: "{{ www_data_path }}"
    owner: "{{ www_owner_deb }}"
    group: "{{ www_group_deb }}"
    mode: "{{ www_index_file_perm }}"

- name: Ensure web server enabled and started
  service:
    name: "apache2"
    state: "{{ web_server_state }}"
    enabled: "{{ web_server_enabled }}"
  notify:
    - Enable_service_at_firewall
    - Restart_firewall