---
# tasks file for web-server-installation-role
- name: Install the correct web server for RHEL
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
  
  notify:
    - Enable_service_at_firewall
    - Restart_firewall