---
# tasks file for web-server-installation-role
- name: Install the correct web server for RHEL
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Ensure web server enabled and started
  service:
    name: "{{ service_name }}"
    state: "{{ web_server_state }}"
    enabled: "{{ web_server_enabled }}"

- handlers:
  - notify: Enable service at firewall
  - notify: Restart firewall