---
# tasks file for web-server-installation-role
- name: Install the correct web server for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Ensure web server enabled and started
  service:
    name: "{{ service_name }}"
    state: "{{ web_server_state }}"
    enabled: "{{ web_server_enabled }}"
    notify:
      - Enable_service_at_firewall
      - Restart_firewall