---
# tasks file for web-server-installation-role
- name: Install the correct web server for RHEL
  import_tasks: redhat.yml
  notify:
    - Enable_service_at_firewall
    - Restart_firewall
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  notify:
    - Enable_service_at_firewall
    - Restart_firewall
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'