---
# handlers file for web-server-installation-role

- name: Enable_service_at_firewall
  firewalld:
      service: http
      state: enabled
      permanent: true

- name: Restart_firewall
  service: 
      name: firewalld 
      state: restarted