---
# handlers file for ftp-server-installation-role

- name: Enable_service_at_firewall
  firewalld:
      service: ftp
      state: enabled
      permanent: true

- name: Enable_pftp_service_at_firewall
  firewalld:
      port: 15000-15500/tcp
      state: enabled
      permanent: true

- name: Restart_firewall
  service: 
      name: firewalld 
      state: restarted