---
# tasks file for ftp-server-installation-role

- name: Install ftp server
  yum:
    name: "{{ ftpd_server }}"
    state: present

- name: Install required packages for sefcontext
  yum:
    name: 
      - python3-libselinux 
      - python3-libsemanage 
      - python3-policycoreutils
  state: present

- name: Selinux options setting
  import_tasks: selinux.yml

- name: Loading ftp server settings
  import_tasks: ftpd.yml

- name: Ensure ftp server enabled and started
  service: 
    name: "{{ ftpd_server }}"
    state: "{{ ftpd_server_state }}"
    enabled: "{{ ftpd_server_enabled }}"
  notify:
    - Enable_service_at_firewall
    - Enable_pftp_service_at_firewall
    - Restart_firewall