---
#- name: Adding public_content_t to selinux
#  sefcontext:
#    target: "/var/ftp/pub/upload"
#    setype: public_content_t
#    reload: yes
#    state: present

- name: Setting ftpd_anon_write for selinux
  seboolean:
    name: ftpd_anon_write
    state: "{{ ftpd_anon_write_state }}"
    persistent: yes

- name: Adding dit to public_content_t to selinux
  sefcontext:
    target: "{{ anonymous_upload }}"
    setype: public_content_t
    reload: yes
    state: present