---
- name: Setting ftpd_anon_write for selinux
  seboolean:
    name: ftpd_anon_write
    state: "{{ ftpd_anon_write_state }}"

- name: Allow passive ftp for selinux
  seboolean:
    name: ftpd_use_passive_mode
    state: yes

- name: Adding dir to public_content_t for selinux
  sefcontext:
    target: '/var/ftp/pub(/.*)?'
    setype: public_content_t
    state: present

- name: Applying dir to public_content_t for selinux
  sefcontext:
    command: restorecon -irv /var/ftp/pub

- name: Adding dir to public_content_rw_t for selinux
  sefcontext:
    target: '/var/ftp/pub/upload(/.*)?'
    setype: public_content_rw_t
    state: present

- name: Applying dir to public_content_rw_t for selinux
  sefcontext:
    command: restorecon -irv /var/ftp/pub/upload
